- name: Markdown-HTML
  uses: ZacJW/markdown-html-action@1.1.1
  with:
    input_files: '[["wildcard*.md"], ["./*.md"]]'
    output_files: '["out1.html", "out2.html"]'
    builtin_stylesheet: 'style.css'
    packages: 'pymdown-extensions'
    extensions: '["pymdownx.extra"]'